[package]
name = "xray-qbrute-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "xray-qbrute"
path = "src/main.rs"

[dependencies]
xray-qbrute-core = { path = "../core", default-features = false }
clap.workspace = true
indicatif.workspace = true
hex.workspace = true
rayon.workspace = true
ctrlc = "3.4.5"

[features]
default = ["scalar", "avx2", "wgpu", "cuda"]
scalar = ["xray-qbrute-core/scalar"]
avx2 = ["xray-qbrute-core/avx2"]
wgpu = ["xray-qbrute-core/wgpu"]
cuda = ["xray-qbrute-core/cuda"]
