allowBuilds:
  '@parcel/watcher@2.6.0': true
  esbuild: false
  esbuild@0.25.12: true

minimumReleaseAgeExclude:
  - '@napi-rs/wasm-runtime@1.2.1'
  - vite@8.2.0

overrides:
  '@napi-rs/wasm-runtime': 1.2.1
